// TypeScript Theme Tokens - For type safety in components
// Actual theme values are defined in CSS @theme directive (main-app/static/styles.css)

export const themeTokens = {
  colors: {
    primary: "var(--color-primary)",
    "primary-hover": "var(--color-primary-hover)",
    "primary-light": "var(--color-primary-light)",
    "on-primary": "var(--color-on-primary)",
    secondary: "var(--color-secondary)",
    "secondary-hover": "var(--color-secondary-hover)",
    "on-secondary": "var(--color-on-secondary)",
    success: "var(--color-success)",
    "success-hover": "var(--color-success-hover)",
    error: "var(--color-error)",
    "error-hover": "var(--color-error-hover)",
    warning: "var(--color-warning)",
    "warning-hover": "var(--color-warning-hover)",
    info: "var(--color-info)",
    "info-hover": "var(--color-info-hover)",
    surface: "var(--color-surface)",
    "surface-variant": "var(--color-surface-variant)",
    "on-surface": "var(--color-on-surface)",
    "on-surface-variant": "var(--color-on-surface-variant)",
    border: "var(--color-border)",
    "border-focus": "var(--color-border-focus)",
    "border-error": "var(--color-border-error)",
  },
  typography: {
    fontFamily: {
      sans: "var(--font-family-sans)",
      mono: "var(--font-family-mono)",
    },
    fontSize: {
      xs: "var(--font-size-xs)",
      sm: "var(--font-size-sm)",
      base: "var(--font-size-base)",
      lg: "var(--font-size-lg)",
      xl: "var(--font-size-xl)",
      "2xl": "var(--font-size-2xl)",
      "3xl": "var(--font-size-3xl)",
      "4xl": "var(--font-size-4xl)",
    },
    fontWeight: {
      normal: "var(--font-weight-normal)",
      medium: "var(--font-weight-medium)",
      semibold: "var(--font-weight-semibold)",
      bold: "var(--font-weight-bold)",
    },
    lineHeight: {
      tight: "var(--line-height-tight)",
      normal: "var(--line-height-normal)",
      relaxed: "var(--line-height-relaxed)",
    },
  },
  spacing: {
    0: "var(--spacing-0)",
    1: "var(--spacing-1)",
    2: "var(--spacing-2)",
    3: "var(--spacing-3)",
    4: "var(--spacing-4)",
    5: "var(--spacing-5)",
    6: "var(--spacing-6)",
    8: "var(--spacing-8)",
    10: "var(--spacing-10)",
    12: "var(--spacing-12)",
    16: "var(--spacing-16)",
  },
  borderRadius: {
    none: "var(--radius-none)",
    sm: "var(--radius-sm)",
    md: "var(--radius-md)",
    lg: "var(--radius-lg)",
    xl: "var(--radius-xl)",
    "2xl": "var(--radius-2xl)",
    full: "var(--radius-full)",
  },
  shadows: {
    sm: "var(--shadow-sm)",
    md: "var(--shadow-md)",
    lg: "var(--shadow-lg)",
    xl: "var(--shadow-xl)",
  },
} as const;
